#pragma once


#define WINDOW_CLASS_NAME L"MARIO BROS. 3"
#define MAIN_WINDOW_TITLE L"MARIO BROS. 3"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(200, 200, 255)
#define SCREEN_WIDTH 760
#define SCREEN_HEIGHT 720

#define MAX_FRAME_RATE 120

#define WORLD_MAP_1_1 101
// CAMERA
#define CAMERA_Y_POSITION 1202
//CGAME
#define MAX_GAME_LINE 1024


#define GAME_FILE_SECTION_UNKNOWN -1
#define GAME_FILE_SECTION_SETTINGS 1
#define GAME_FILE_SECTION_SCENES 2
#define GAME_FILE_SECTION_SPRITES 3

//TEXTURE
#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define DEFAULT_FRAME_TIME 100

//SCENE
#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6

#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_PIPE	2
#define OBJECT_TYPE_GHOST	3
#define OBJECT_TYPE_CLOUD	4

#define OBJECT_TYPE_PORTAL	50

#define MAX_SCENE_LINE 1024

//CGAME
#define DIRECTINPUT_VERSION 0x0800
#define KEYBOARD_BUFFER_SIZE 1024

//MARIO
#define MARIO_WALKING_ACCELERATION	0.000376f
#define MARIO_RUNNING_ACCELERATION	0.000288f
#define MARIO_SKID_ACCELERATION 0.001104f

#define MARIO_WALK_DRAG_FORCE	0.0002906f
#define MARIO_RUN_DRAG_FORCE	0.0006266f

#define MARIO_WALKING_SPEED		0.12f 
#define MARIO_RUNNING_SPEED	0.4f

#define MARIO_PUSH_FORCE 0.00286f
#define MARIO_JUMP_FORCE 0.3f
#define MARIO_HIGH_JUMP_FORCE 0.45f
#define MARIO_SUPER_JUMP_FORCE  1.08f

#define MARIO_JUMP_SPEED_Y		0.8f
#define MARIO_JUMP_DEFLECT_SPEED 0.2f
#define MARIO_GRAVITY			0.00193f
#define MARIO_DIE_DEFLECT_SPEED	 0.5f

#define MARIO_STATE_WALKING 1
#define MARIO_STATE_RUNNING 2

#define MARIO_CROUNCH 3
#define MARIO_SWIM 4

#define MARIO_STATE_IDLE			0
#define MARIO_STATE_SKID	202

#define MARIO_STATE_JUMP_IDLE			300
#define MARIO_STATE_JUMP			301
#define MARIO_STATE_HIGH_JUMP	302
#define MARIO_STATE_SUPER_JUMP	303
#define MARIO_STATE_FALL	304

#define MARIO_STATE_DIE				400
#define MARIO_STATE_KICK	500

#define MARIO_ANI_SMALL_IDLE	102
#define MARIO_ANI_SMALL_WALKING		103
#define MARIO_ANI_SMALL_RUNNING		106
#define MARIO_ANI_SMALL_FALL	104
#define MARIO_ANI_SMALL_JUMP		108
#define MARIO_ANI_SMALL_SKID	105

#define MARIO_ANI_BIG_IDLE		121
#define MARIO_ANI_BIG_WALKING		123
#define MARIO_ANI_BIG_RUNNING		127
#define MARIO_ANI_BIG_JUMP		130
#define MARIO_ANI_BIG_SKID		126


#define MARIO_ANI_RACOON_WALKING	155
#define MARIO_ANI_RACOON_IDLE	154
#define MARIO_ANI_RACOON_RUNNING		159
#define MARIO_ANI_RACOON_JUMP		162
#define MARIO_ANI_RACOON_SKID		158

#define MARIO_ANI_FIRE_IDLE	196
#define MARIO_ANI_FIRE_WALKING	197
#define MARIO_ANI_FIRE_RUNNING		203
#define MARIO_ANI_FIRE_JUMP		206
#define MARIO_ANI_FIRE_SKID		200


#define MARIO_ANI_DIE				999

#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2
#define	MARIO_LEVEL_RACOON		3
#define	MARIO_LEVEL_FIRE		4

#define MARIO_BIG_BBOX_WIDTH  45
#define MARIO_BIG_BBOX_HEIGHT 81

#define MARIO_SMALL_BBOX_WIDTH  39
#define MARIO_SMALL_BBOX_HEIGHT 48

#define MARIO_RACOON_BBOX_WIDTH  63
#define MARIO_RACOON_BBOX_HEIGHT 84

#define MARIO_FIRE_BBOX_WIDTH 48
#define MARIO_FIRE_BBOX_HEIGHT 81


#define MARIO_UNTOUCHABLE_TIME 5000

//KOOPAS
#define KOOPAS_WALKING_SPEED 0.03f;

#define KOOPAS_BBOX_WIDTH 16
#define KOOPAS_BBOX_HEIGHT 26
#define KOOPAS_BBOX_HEIGHT_DIE 16

#define KOOPAS_STATE_WALKING 100
#define KOOPAS_STATE_DIE 200

#define KOOPAS_ANI_WALKING_LEFT 0
#define KOOPAS_ANI_WALKING_RIGHT 1
#define KOOPAS_ANI_DIE 2

//GOOMBA
#define GOOMBA_WALKING_SPEED 0.05f;

#define GOOMBA_BBOX_WIDTH 16
#define GOOMBA_BBOX_HEIGHT 15
#define GOOMBA_BBOX_HEIGHT_DIE 9

#define GOOMBA_STATE_WALKING 100
#define GOOMBA_STATE_DIE 200

#define GOOMBA_ANI_WALKING 0
#define GOOMBA_ANI_DIE 1


